export const BookData = [
    {
        id: 0,
        book_name: "Basic Electrical Engineering (MU-2019)",
        book_description: "This book is designed for the first-year engineering students of University of Mumbai. The crisp yet complete explanation of topics will help the students easily understand the basic concepts. A plethora of various solved examples and exercise problems will enable students to practice better and excel in examinations. Salient features: 1. Follows Blooms taxonomy 2. Solutions of mu examination Question papers from 2012 to 2018 placed appropriately within the book 3. ",
        book_url: "https://m.media-amazon.com/images/I/41pRH86A+7L._AC_UF1000,1000_QL80_.jpg",
        print_length: "345 pages",
        language: "English",
        author_name: "McGraw Hill",
        price: "305",
    },
    {
        id: 1,
        book_name: "Engineering Mechanics by MD Dayal ",
        book_description: "Engineering Mechanics by M.D. Dayal is a comprehensive textbook that provides a fundamental understanding of the principles and concepts of engineering mechanics. It covers topics such as statics, dynamics, and the mechanics of materials, making it a valuable resource for engineering students seeking to build a strong foundation in this essential discipline.",
        book_url: "https://m.media-amazon.com/images/I/711dJ3tBPxL._SY342_.jpg",
        print_length: "500 pages",
        language: "English",
        author_name: "Wiley",
        price: "593",
    },
    {
        id: 2,
        book_name: "Engineering Mathematics -1 ",
        book_description: "Engineering Mathematics - 1 is a foundational course in engineering education that provides students with essential mathematical tools and concepts to solve engineering problems. This course typically covers topics such as calculus, linear algebra, differential equations, and complex numbers",
        book_url: "https://m.media-amazon.com/images/I/81MnJNmq0kL._SY342_.jpg",
        print_length: "236 pages",
        language: "English",
        author_name: " G.V.Kumbhojkar",
        price: "630",
    },
    {
        id: 3,
        book_name: "Applied Physics, Vol-1, Fourth Edition ",
        book_description: "Applied Physics-Vol 1 has been written keeping in mind First Year Engineering Students of Four Year Degree Course (B.E./B.Tech.). This book will develop interest in the subject of Applied Physics and students can look forward for securing higher and better scores. Each topic begins with an Introduction in a simple and easy to understand language. More illustrative diagrams and examples help in better understanding.",
        book_url: "https://m.media-amazon.com/images/I/81N+adWtFuL._SY342_.jpg",
        print_length: "240 pages",
        language: "English",
        author_name: " I K International Publishing House",
        price: "500",
    },
    {
        id: 4,
        book_name: "Engineering Applied Chemistry Textbook ",
        book_description: "This book is primarily focused on the undergraduate students of engineering and science. It has been believed that education in chemistry for Engineering students will train us to think in terms of molecules and their interactions. The book aims to impart as in-depth understanding of Chemistry as Applied to Engineers",
        book_url: "https://m.media-amazon.com/images/I/61ol7jUDlKL._SY342_.jpg",
        print_length: "248 pages",
        language: "English",
        author_name: "Notion Press",
        price: "286",
    },
    {
        id: 5,
        book_name: "TA Textbook Of Applied Mathematics-Ii by Dr. Hari Arora , S.K. Kataria & Sons",
        book_description: "A Textbook of Applied Mathematics-II by Dr. Hari Arora is a comprehensive educational resource published by S.K. Kataria & Sons. This book delves into the practical applications of mathematical concepts, providing students with a solid foundation in applied mathematics through clear explanations and examples, making it an essential tool for students and professionals in various fields.",
        book_url: "https://www.meripustak.com/MeripustakStatic/FullImage/A-Textbook-Of-Applied-Mathematics-Ii_346064.jpg",
        print_length: "425 pages",
        language: "English",
        author_name: " Dr. Hari Arora ",
        price: "340",
    },
    {
        id: 6,
        book_name: "Applied Physics - 2",
        book_description: "Applied Physics is a branch of physics that focuses on utilizing the principles and theories of physics to solve real-world problems and develop practical technologies. It bridges the gap between fundamental physics theories and their practical applications in various industries, such as engineering, electronics, materials science, and medicine.",
        book_url: "https://m.media-amazon.com/images/I/51Z9p5AecCL.SX307_BO1,204,203,200.jpg",
        print_length: "492 pages",
        language: "English",
        author_name: "D.choudhri",
        price: "390",
    },
    {
        id: 7,
        book_name: "Textbook Applied Chemistry -2: First Year Engineering Semester 2 (University of Mumbai)",
        book_description: "In this Text Book, the Subject: “Applied Chemistry-II”, an emphasis has been given on scientifically based knowledge, information and tried our level best to present it in much simplified manners; so that Students can understand easily and use this handbook as their quick-memorizer and ready reckoner.",
        book_url: "https://m.media-amazon.com/images/I/7161vWvDaIL.SY342.jpg",
        print_length: "245 pages",
        language: "English",
        author_name: "Dr. Varadbal Mhatre",
        price: "284",
    },
    {
        id: 8,
        book_name: "Let Us C: Authentic guide to C programming language - 19th Edition",
        book_description: "Over 3 Million Copies Sold...The new edition of this classic book has been thoroughly revamped but remains faithful to the principles that have established it as a favourite amongst students, teachers and software professionals round the world.",
        book_url: "https://m.media-amazon.com/images/I/81ZPcK6HpuL.SY342.jpg",
        print_length: "508 pages",
        language: "English",
        author_name: "Dariya Ganj",
        price: "340",
    },
    {
        id: 9,
        book_name: "Engineering Drawing",
        book_description: "Engineering Drawing provides a detailed study of plane and solid geometry the two salient topics of study in almost any branch of engineering. This particular textbook follows the first angle method of orthographic projection although the third angle method of orthographic projection has been touched upon too. The topics in this chapter have been presented in a clear concise and easily accessible format with the print in two colours ",
        book_url: "https://m.media-amazon.com/images/I/91t+7QSEtYL.SY342.jpg ",
        print_length: "736 pages",
        language: "English",
        author_name: "Charotar Publishing House",
        price: "449",
    },
    {
        id: 10,
        book_name: "Engineering Mathematics-III (MU) Computer Engg & IT Engg Semester-III [Paperback] G V Kumbhojkar ",
        book_description: "textbook",
        book_url: "https://m.media-amazon.com/images/I/91gV2rwBoeL.SY342.jpg",
        print_length: "208 pages",
        language: "English",
        author_name: "G.V.Kumbhojkar",
        price: "680",
    },
    {
        id: 11,
        book_name: "Codeless Data Structures and Algorithms: Learn DSA Without Writing a Single Line of Code",
        book_description: "In the era of self-taught developers and programmers, essential topics in the industry are frequently learned without a formal academic foundation. A solid grasp of data structures and algorithms (DSA) is imperative for anyone looking to do professional software development and engineering, but classes in the subject can be dry or spend too much time on theory and unnecessary readings.",
        book_url: "https://m.media-amazon.com/images/I/51Nv6BP9YSL.SY342.jpg",
        print_length: "146 pages",
        language: "English",
        author_name: "Apress; 1st ed. edition",
        price: "3,511",
    },
    {
        id: 12,
        book_name: "Database Management Systems (Dbms)",
        book_description: "Reading books is a kind of enjoyment. Reading books is a good habit. We bring you a different kinds of books. You can carry this book where ever you want. It is easy to carry. It can be an ideal gift to yourself and to your loved ones. Care instruction keep away from fire.",
        book_url: "https://m.media-amazon.com/images/I/91zPPwURKUL.SY342.jpg",
        print_length: "688 pages",
        language: "English",
        author_name: " S Chand Publishing; Fifth edition ",
        price: "405",
    },
    {
        id: 13,
        book_name: "Computer Network and Network Design For MU B.E. IT Engineering Sem 4 ",
        book_description: "Text Book",
        book_url: "https://m.media-amazon.com/images/I/81dYqe12xUL.SY342.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "J.S Katre",
        price: "432",
    },
    {
        id: 14,
        book_name: "Linux Operating System Success in A Day",
        book_description: "LINUX Operating System success in a day: Beginners guide to fast, easy and efficient learning of LINUX Operating Systems What is Linux? Need to know everything about OS? How about who are the largest distributors of Linux? Are you wanting to get going on Linux running? How about desktop environments do you care which is the best?",
        book_url: "https://m.media-amazon.com/images/I/81vNeNZKxZL.SY342.jpg",
        print_length: "52 pages",
        language: "English",
        author_name: "Sam Key",
        price: "2240",
    },
    {
        id: 15,
        book_name: "Automata Theory and Formal Languages: Fundamental Notions, Theorems, and Techniques (Undergraduate Topics in Computer Science) ",
        book_description: "Knowledge of automata theory and formal languages is crucial for understanding human-computer interaction, as well as for understanding the various processes that take place when manipulating knowledge if that knowledge is, indeed, expressed as sentences written in a suitably formalized language. In particular, it is at the basis of the theory of parsing, which plays an important role in language translation, compiler construction, and knowledge manipulation in general.",
        book_url: "https://m.media-amazon.com/images/I/61wvQKEU0OL.SY342.jpg",
        print_length: "560 pages",
        language: "English",
        author_name: "Alberto Pettorossi ",
        price: "4363",
    },
    {
        id: 16,
        book_name: "Modern Computer Architecture and Organization - Second Edition: Learn x86, ARM, and RISC-V architectures and the design of smartphones, PCs, and cloud servers",
        book_description: "A no-nonsense, practical guide to current and future processor and computer architectures that enables you to design computer systems and develop better software applications across a variety of domains",
        book_url: "https://m.media-amazon.com/images/I/71RZgYOIZtL.SY342.jpg",
        print_length: "666 pages",
        language: "English",
        author_name: "Jim Ledin,Dave Farley",
        price: "3006",
    }
]
